# Generated by Django 2.1.1 on 2018-12-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181201_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='album',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='artist',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='song',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
