# Generated by Django 2.1.1 on 2018-12-03 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20181201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=2000)),
                ('album', models.CharField(default='', max_length=100)),
                ('song', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
                ('artwork', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('public', models.BooleanField(default=False)),
                ('fromUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
