# Generated by Django 2.1.1 on 2018-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181204_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentPk',
            field=models.IntegerField(default='-1'),
        ),
    ]
